-- ============================================================
-- BAZA DANYCH I ROZWIĄZANIE - LibreOffice / OpenOffice Base
-- Silnik: HSQLDB (wbudowany)
-- Uwagi:
--   - literały dat: {d 'YYYY-MM-DD'}
--   - nazwy UPPER CASE (Base automatycznie konwertuje)
-- ============================================================

-- ============================================================
-- ZADANIE 0: UTWORZENIE TABEL I WSTAWIENIE DANYCH
-- ============================================================

CREATE TABLE AUTHORS (
AUTHOR_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
BIRTH_YEAR INTEGER
);

CREATE TABLE MEMBERS (
MEMBER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
JOIN_DATE DATE
);

CREATE TABLE BOOKS (
BOOK_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
TITLE VARCHAR(50),
AUTHOR_ID INTEGER,
PUBLISHED_YEAR INTEGER,
GENRE VARCHAR(50),
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

CREATE TABLE LOANS(
LOAN_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
BOOK_ID INTEGER,
MEMBER_ID INTEGER,
LOAN_DATE DATE,
RETURN_DATE DATE,
FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
);

INSERT INTO AUTHORS (FIRST_NAME, LAST_NAME, BIRTH_YEAR) VALUES ('J.K.', 'Rowling', 1965);
INSERT INTO AUTHORS (FIRST_NAME, LAST_NAME, BIRTH_YEAR) VALUES ('George', 'Orwell', 1903);
INSERT INTO AUTHORS (FIRST_NAME, LAST_NAME, BIRTH_YEAR) VALUES ('Andrzej', 'Sapkowski', 1948);
INSERT INTO AUTHORS (FIRST_NAME, LAST_NAME, BIRTH_YEAR) VALUES ('Henryk', 'Sienkiewicz', 1846);
INSERT INTO AUTHORS (FIRST_NAME, LAST_NAME, BIRTH_YEAR) VALUES ('Adam', 'Mickiewicz', 1798);

INSERT INTO BOOKS (TITLE, AUTHOR_ID, PUBLISHED_YEAR, GENRE) VALUES ('Harry Potter i Kamień Filozoficzny', 1, 1997, 'Fantasy');
INSERT INTO BOOKS (TITLE, AUTHOR_ID, PUBLISHED_YEAR, GENRE) VALUES ('Harry Potter i Komnata Tajemnic', 1, 1998, 'Fantasy');
INSERT INTO BOOKS (TITLE, AUTHOR_ID, PUBLISHED_YEAR, GENRE) VALUES ('Rok 1984', 2, 1949, 'Dystopia');
INSERT INTO BOOKS (TITLE, AUTHOR_ID, PUBLISHED_YEAR, GENRE) VALUES ('Folwark zwierzęcy', 2, 1945, 'Satyria');
INSERT INTO BOOKS (TITLE, AUTHOR_ID, PUBLISHED_YEAR, GENRE) VALUES ('Wiedźmin: Ostatnie życzenie', 3, 1993, 'Fantasy');
INSERT INTO BOOKS (TITLE, AUTHOR_ID, PUBLISHED_YEAR, GENRE) VALUES ('Wiedźmin: Krew elfów', 3, 1994, 'Fantasy');
INSERT INTO BOOKS (TITLE, AUTHOR_ID, PUBLISHED_YEAR, GENRE) VALUES ('Quo Vadis', 4, 1896, 'Powieść historyczna');
INSERT INTO BOOKS (TITLE, AUTHOR_ID, PUBLISHED_YEAR, GENRE) VALUES ('Pan Tadeusz', 5, 1834, 'Epopeja');
INSERT INTO BOOKS (TITLE, AUTHOR_ID, PUBLISHED_YEAR, GENRE) VALUES ('Python dla początkujących', 3, 2021, 'Edukacja');
INSERT INTO BOOKS (TITLE, AUTHOR_ID, PUBLISHED_YEAR, GENRE) VALUES ('SQL w praktyce', 3, 2023, 'Edukacja');

INSERT INTO MEMBERS (FIRST_NAME, LAST_NAME, JOIN_DATE) VALUES ('Jan', 'Kowalski', {d '2023-01-15'});
INSERT INTO MEMBERS (FIRST_NAME, LAST_NAME, JOIN_DATE) VALUES ('Anna', 'Nowak', {d '2023-03-22'});
INSERT INTO MEMBERS (FIRST_NAME, LAST_NAME, JOIN_DATE) VALUES ('Piotr', 'Wiśniewski', {d '2024-02-10'});
INSERT INTO MEMBERS (FIRST_NAME, LAST_NAME, JOIN_DATE) VALUES ('Katarzyna', 'Lewandowska', {d '2024-05-01'});
INSERT INTO MEMBERS (FIRST_NAME, LAST_NAME, JOIN_DATE) VALUES ('Marek', 'Zieliński', {d '2022-11-30'});

INSERT INTO LOANS (BOOK_ID, MEMBER_ID, LOAN_DATE, RETURN_DATE) VALUES (1, 1, {d '2025-01-10'}, {d '2025-01-20'});
INSERT INTO LOANS (BOOK_ID, MEMBER_ID, LOAN_DATE, RETURN_DATE) VALUES (3, 2, {d '2025-02-05'}, NULL);
INSERT INTO LOANS (BOOK_ID, MEMBER_ID, LOAN_DATE, RETURN_DATE) VALUES (5, 1, {d '2025-02-15'}, {d '2025-02-28'});
INSERT INTO LOANS (BOOK_ID, MEMBER_ID, LOAN_DATE, RETURN_DATE) VALUES (7, 3, {d '2025-03-01'}, NULL);
INSERT INTO LOANS (BOOK_ID, MEMBER_ID, LOAN_DATE, RETURN_DATE) VALUES (2, 4, {d '2025-03-10'}, {d '2025-03-18'});
INSERT INTO LOANS (BOOK_ID, MEMBER_ID, LOAN_DATE, RETURN_DATE) VALUES (9, 2, {d '2025-04-01'}, NULL);
INSERT INTO LOANS (BOOK_ID, MEMBER_ID, LOAN_DATE, RETURN_DATE) VALUES (10, 5, {d '2025-04-05'}, {d '2025-04-20'});
INSERT INTO LOANS (BOOK_ID, MEMBER_ID, LOAN_DATE, RETURN_DATE) VALUES (4, 1, {d '2025-04-15'}, NULL);

-- ============================================================
-- ZADANIE 1:
-- ============================================================
SELECT FIRST_NAME, LAST_NAME FROM AUTHORS;

-- ============================================================
-- ZADANIE 2:
-- ============================================================
SELECT B.TITLE, A.FIRST_NAME, A.LAST_NAME 
FROM BOOKS B 
JOIN AUTHORS A ON B.AUTHOR_ID = A.AUTHOR_ID;

-- ============================================================
-- ZADANIE 3:
-- ============================================================
INSERT INTO AUTHORS (FIRST_NAME, LAST_NAME, BIRTH_YEAR) VALUES ('Adam', 'Mickiewicz', 1798);

-- ============================================================
-- ZADANIE 4:
-- ============================================================
SELECT TITLE, PUBLISHED_YEAR, GENRE 
FROM BOOKS 
WHERE PUBLISHED_YEAR > 2000;

-- ============================================================
-- ZADANIE 5:
-- ============================================================
SELECT DISTINCT M.FIRST_NAME, M.LAST_NAME 
FROM MEMBERS M 
JOIN LOANS L ON M.MEMBER_ID = L.MEMBER_ID 
WHERE L.RETURN_DATE IS NULL;

-- ============================================================
-- ZADANIE 6:
-- ============================================================
INSERT INTO LOANS (BOOK_ID, MEMBER_ID, LOAN_DATE, RETURN_DATE) VALUES (3, 2, CURRENT_DATE, NULL);

-- ============================================================
-- ZADANIE 7:
-- ============================================================
UPDATE LOANS SET RETURN_DATE = CURRENT_DATE WHERE LOAN_ID = 5;

-- ============================================================
-- ZADANIE 8:
-- ============================================================
SELECT B.TITLE, L.RETURN_DATE 
FROM BOOKS B 
LEFT JOIN LOANS L ON B.BOOK_ID = L.BOOK_ID;
-- (Uwaga: Poprawiono błąd z oryginalnego pliku, gdzie było b.book_id = l.loan_id)

-- ============================================================
-- ZADANIE 9:
-- ============================================================
SELECT A.FIRST_NAME, A.LAST_NAME, COUNT(B.BOOK_ID) AS LICZBA_KSIAZEK 
FROM AUTHORS A 
LEFT JOIN BOOKS B ON A.AUTHOR_ID = B.AUTHOR_ID 
GROUP BY A.AUTHOR_ID, A.FIRST_NAME, A.LAST_NAME;

-- ============================================================
-- ZADANIE 10:
-- ============================================================
SELECT B.TITLE 
FROM BOOKS B 
JOIN LOANS L ON B.BOOK_ID = L.BOOK_ID 
JOIN MEMBERS M ON L.MEMBER_ID = M.MEMBER_ID 
WHERE M.FIRST_NAME = 'Jan' AND M.LAST_NAME = 'Kowalski';

